/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Classes.Man;
import org.example.Classes.Person;
import org.example.Classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Man mohan= new Man("Mohan",30, "Belagavi","India");
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan =(Person) Proxy.newProxyInstance(mohanClassLoader,interfaces,new PersonInvocationHandler(mohan));
        proxyMohan.introduce("Mohan");
    }
}